//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ched.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ched.Localization.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 エクスポートが完了しました。 的本地化字符串。
        /// </summary>
        public static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エクスポートに失敗しました。 的本地化字符串。
        /// </summary>
        public static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編集中のデータは破棄されますがよろしいですか？ 的本地化字符串。
        /// </summary>
        public static string FileDiscardConfirmation {
            get {
                return ResourceManager.GetString("FileDiscardConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ファイルの読み込み中にエラーが発生しました。 的本地化字符串。
        /// </summary>
        public static string FileLoadError {
            get {
                return ResourceManager.GetString("FileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ファイルにアクセスできません。 的本地化字符串。
        /// </summary>
        public static string FileNotAccessible {
            get {
                return ResourceManager.GetString("FileNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在のバージョンでは開けないファイルです。 的本地化字符串。
        /// </summary>
        public static string FileNotCompatible {
            get {
                return ResourceManager.GetString("FileNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 古いバージョンで作成されたファイルです。
        ///バージョンアップしてよろしいですか？
        ///(以前のバージョンでは開けなくなります。) 的本地化字符串。
        /// </summary>
        public static string FileUpgradeNeeded {
            get {
                return ResourceManager.GetString("FileUpgradeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 インポートが完了しました。 的本地化字符串。
        /// </summary>
        public static string ImportComplete {
            get {
                return ResourceManager.GetString("ImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 インポートに失敗しました。 的本地化字符串。
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子定義が無効です。イベントが小節の先頭に配置されていることを確認してください。(場所: 第{0}拍付近) 的本地化字符串。
        /// </summary>
        public static string InvalidTimeSignature {
            get {
                return ResourceManager.GetString("InvalidTimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 譜面プロパティから音源ファイルを指定してください。 的本地化字符串。
        /// </summary>
        public static string MusicSourceNull {
            get {
                return ResourceManager.GetString("MusicSourceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エクスポートが実行されていません。 的本地化字符串。
        /// </summary>
        public static string NotExported {
            get {
                return ResourceManager.GetString("NotExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出力先を指定してください。 的本地化字符串。
        /// </summary>
        public static string OutputPathRequired {
            get {
                return ResourceManager.GetString("OutputPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プラグインの実行中にエラーが発生しました。 的本地化字符串。
        /// </summary>
        public static string PluginException {
            get {
                return ResourceManager.GetString("PluginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下のプラグインの読み込みに失敗しました。DLLファイルがブロックされている可能性があります。 的本地化字符串。
        /// </summary>
        public static string PluginLoadError {
            get {
                return ResourceManager.GetString("PluginLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下のプラグインは現在のバージョンに対応していない可能性があります。プラグイン機能は無効化されます。 的本地化字符串。
        /// </summary>
        public static string PluginNotSupported {
            get {
                return ResourceManager.GetString("PluginNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プレビュー中にエラーが発生しました。 的本地化字符串。
        /// </summary>
        public static string PreviewException {
            get {
                return ResourceManager.GetString("PreviewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 簡易プレビューが利用できない環境です。 的本地化字符串。
        /// </summary>
        public static string PreviewNotSupported {
            get {
                return ResourceManager.GetString("PreviewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波形を表示 的本地化字符串。
        /// </summary>
        public static string ShowWaveForm {
            get {
                return ResourceManager.GetString("ShowWaveForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音源ファイルが見つかりません。 的本地化字符串。
        /// </summary>
        public static string SourceFileNotFound {
            get {
                return ResourceManager.GetString("SourceFileNotFound", resourceCulture);
            }
        }
    }
}
