//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ched.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ched.Localization.MainFormStrings", typeof(MainFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 最終ノートで停止 的本地化字符串。
        /// </summary>
        public static string AbortAtLastNote {
            get {
                return ResourceManager.GetString("AbortAtLastNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自由記述欄 的本地化字符串。
        /// </summary>
        public static string AdditionalData {
            get {
                return ResourceManager.GetString("AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 振り下げAIR 的本地化字符串。
        /// </summary>
        public static string AirDown {
            get {
                return ResourceManager.GetString("AirDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 振り下げ左AIR 的本地化字符串。
        /// </summary>
        public static string AirLeftDown {
            get {
                return ResourceManager.GetString("AirLeftDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 振り上げ左AIR 的本地化字符串。
        /// </summary>
        public static string AirLeftUp {
            get {
                return ResourceManager.GetString("AirLeftUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 振り下げ右AIR 的本地化字符串。
        /// </summary>
        public static string AirRightDown {
            get {
                return ResourceManager.GetString("AirRightDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 振り上げ右AIR 的本地化字符串。
        /// </summary>
        public static string AirRightUp {
            get {
                return ResourceManager.GetString("AirRightUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 振り上げAIR 的本地化字符串。
        /// </summary>
        public static string AirUp {
            get {
                return ResourceManager.GetString("AirUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アーティスト 的本地化字符串。
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本情報 的本地化字符串。
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 譜面プロパティ 的本地化字符串。
        /// </summary>
        public static string BookProperty {
            get {
                return ResourceManager.GetString("BookProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参照 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 キャンセル 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クリア 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 コマンド 的本地化字符串。
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 コピー 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択したイベントのコピー 的本地化字符串。
        /// </summary>
        public static string CopySelectedEvents {
            get {
                return ResourceManager.GetString("CopySelectedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 カスタム 的本地化字符串。
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切り取り 的本地化字符串。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択したイベントを切り取る 的本地化字符串。
        /// </summary>
        public static string CutSelectedEvents {
            get {
                return ResourceManager.GetString("CutSelectedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 イベント削除 的本地化字符串。
        /// </summary>
        public static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 難易度 的本地化字符串。
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分 的本地化字符串。
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編集(&amp;E) 的本地化字符串。
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消しゴム 的本地化字符串。
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 終了 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エクスポート 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ファイル(&amp;F) 的本地化字符串。
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択範囲内ノーツを反転 的本地化字符串。
        /// </summary>
        public static string FlipSelectedNotes {
            get {
                return ResourceManager.GetString("FlipSelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生時にスクロール 的本地化字符串。
        /// </summary>
        public static string FollowWhenPlaying {
            get {
                return ResourceManager.GetString("FollowWhenPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ヘルプを開く 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ヘルプ(&amp;H) 的本地化字符串。
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ハイスピード 的本地化字符串。
        /// </summary>
        public static string HighSpeed {
            get {
                return ResourceManager.GetString("HighSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 インポート 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AIR-ACTIONとAIRを同時に追加する 的本地化字符串。
        /// </summary>
        public static string InsertAirWithAirAction {
            get {
                return ResourceManager.GetString("InsertAirWithAirAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挿入(&amp;I) 的本地化字符串。
        /// </summary>
        public static string InsertMenu {
            get {
                return ResourceManager.GetString("InsertMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先頭に1小節の空白を挿入する 的本地化字符串。
        /// </summary>
        public static string InsertSingleBlankAtBeginning {
            get {
                return ResourceManager.GetString("InsertSingleBlankAtBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ジャケットファイル 的本地化字符串。
        /// </summary>
        public static string JacketFile {
            get {
                return ResourceManager.GetString("JacketFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ショートカット設定 的本地化字符串。
        /// </summary>
        public static string KeyboardShortcuts {
            get {
                return ResourceManager.GetString("KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ショートカットキー 的本地化字符串。
        /// </summary>
        public static string KeyCombination {
            get {
                return ResourceManager.GetString("KeyCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レベル 的本地化字符串。
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音源情報 的本地化字符串。
        /// </summary>
        public static string MusicInformation {
            get {
                return ResourceManager.GetString("MusicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レーン幅を狭める 的本地化字符串。
        /// </summary>
        public static string NarrowLaneWidth {
            get {
                return ResourceManager.GetString("NarrowLaneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新規作成 的本地化字符串。
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ノーツデザイナー 的本地化字符串。
        /// </summary>
        public static string NotesDesigner {
            get {
                return ResourceManager.GetString("NotesDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 オフセット 的本地化字符串。
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開く 的本地化字符串。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貼り付け 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択したイベントの貼り付け 的本地化字符串。
        /// </summary>
        public static string PasteEvents {
            get {
                return ResourceManager.GetString("PasteEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反転貼り付け 的本地化字符串。
        /// </summary>
        public static string PasteFlipped {
            get {
                return ResourceManager.GetString("PasteFlipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ペン 的本地化字符串。
        /// </summary>
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生/停止 的本地化字符串。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半分の速度で再生 的本地化字符串。
        /// </summary>
        public static string PlayAtHalfSpeed {
            get {
                return ResourceManager.GetString("PlayAtHalfSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生(&amp;P) 的本地化字符串。
        /// </summary>
        public static string PlayMenu {
            get {
                return ResourceManager.GetString("PlayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プラグイン 的本地化字符串。
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プレビュー速度 的本地化字符串。
        /// </summary>
        public static string PreviewSpeed {
            get {
                return ResourceManager.GetString("PreviewSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 記録(追加) 的本地化字符串。
        /// </summary>
        public static string RecordAdd {
            get {
                return ResourceManager.GetString("RecordAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消す 的本地化字符串。
        /// </summary>
        public static string RecordClear {
            get {
                return ResourceManager.GetString("RecordClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非表示 的本地化字符串。
        /// </summary>
        public static string RecordHide {
            get {
                return ResourceManager.GetString("RecordHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入力装置 的本地化字符串。
        /// </summary>
        public static string RecordInput {
            get {
                return ResourceManager.GetString("RecordInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 記録(&amp;R) 的本地化字符串。
        /// </summary>
        public static string RecordMenu {
            get {
                return ResourceManager.GetString("RecordMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 記録(上書き) 的本地化字符串。
        /// </summary>
        public static string RecordOverwrite {
            get {
                return ResourceManager.GetString("RecordOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示 的本地化字符串。
        /// </summary>
        public static string RecordShow {
            get {
                return ResourceManager.GetString("RecordShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 やり直す 的本地化字符串。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択範囲内イベントを削除 的本地化字符串。
        /// </summary>
        public static string RemoveEvents {
            get {
                return ResourceManager.GetString("RemoveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択範囲内ノーツを削除 的本地化字符串。
        /// </summary>
        public static string RemoveSelectedNotes {
            get {
                return ResourceManager.GetString("RemoveSelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初期化 的本地化字符串。
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生終了時に戻る 的本地化字符串。
        /// </summary>
        public static string ReturnWhenPlayFinished {
            get {
                return ResourceManager.GetString("ReturnWhenPlayFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名前を付けて保存 的本地化字符串。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上書き保存 的本地化字符串。
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 譜面プレビュー 的本地化字符串。
        /// </summary>
        public static string ScorePreview {
            get {
                return ResourceManager.GetString("ScorePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 すべて選択 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択 的本地化字符串。
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最初から現在位置まで選択 的本地化字符串。
        /// </summary>
        public static string SelectToBeginning {
            get {
                return ResourceManager.GetString("SelectToBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在位置から最後まで選択 的本地化字符串。
        /// </summary>
        public static string SelectToEnd {
            get {
                return ResourceManager.GetString("SelectToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SLIDE(湾曲) 的本地化字符串。
        /// </summary>
        public static string SlideCurve {
            get {
                return ResourceManager.GetString("SlideCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SLIDE(中継点) 的本地化字符串。
        /// </summary>
        public static string SlideStep {
            get {
                return ResourceManager.GetString("SlideStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音源ファイル 的本地化字符串。
        /// </summary>
        public static string SoundFile {
            get {
                return ResourceManager.GetString("SoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スプリット 的本地化字符串。
        /// </summary>
        public static string SplitLine {
            get {
                return ResourceManager.GetString("SplitLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子 的本地化字符串。
        /// </summary>
        public static string TimeSignature {
            get {
                return ResourceManager.GetString("TimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タイトル 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元に戻す 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 バージョン情報 的本地化字符串。
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示(&amp;V) 的本地化字符串。
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レーン幅を広げる 的本地化字符串。
        /// </summary>
        public static string WidenLaneWidth {
            get {
                return ResourceManager.GetString("WidenLaneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拡大 的本地化字符串。
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 縮小 的本地化字符串。
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
